services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/application
    ports:
      - 3000:3000
      - 8000:8000
      - 9999:9999

  mysql:
    image: mysql:8.1
    platform: linux/x86_64
    volumes:
      - ./mysql:/var/lib/mysql
      - ./apps/resource/seeds:/var/lib/mysql-files
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT}:3306
    env_file: .env
    environment:
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      #MYSQL_USER: ${DB_USER}
      #MYSQL_PASSWORD: ${DB_PASS}
