name: CI
on:
  pull_request:
    types: synchronize
    branches: develop

env:
  NODE_VERSION: 18.17.*
  LAUNCH_CSPELL: off # Launch CSpell. [ on, off ]
  LAUNCH_ESLINT: off # Launch ESLint. [ on, off ]
  LAUNCH_STYLELINT: off # Launch Stylelint. [ on, off ]
  LAUNCH_TYPECHECK: off # Launch tsc. [ on, off ]
  LAUNCH_JEST: off # Launch Jest. [ on, off ]
  LAUNCH_BUILD: off # Launch Build. [ on, off ]

jobs:
  setup:
    name: Setup Module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node Modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-
      - name: Install Dependencies
        run: yarn

  cspell:
    name: CSpell
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Do CSpell
        if: env.LAUNCH_CSPELL == 'on'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn cspell --dot --no-must-find-files "**/*" \
          | reviewdog -level=warning -efm="%f:%l:%c - %m" -reporter=github-pr-review
      - name: Displayed CSpell Failure on Checks
        if: env.LAUNCH_CSPELL == 'on'
        run: yarn cspell --dot --no-must-find-files "**/*"

  eslint:
    name: ESlint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Do ESLint
        if: env.LAUNCH_ESLINT == 'on'
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          eslint_flags: "./**/*.{ts,js}"
      - name: Displayed ESLINT Failure on Checks
        if: env.LAUNCH_ESLINT == 'on'
        run: yarn lint

  stylelint:
    name: Stylelint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Do Stylelint
        if: env.LAUNCH_STYLELINT == 'on'
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          stylelint_input: "./**/*.scss"
      - name: Displayed Stylelint Failure on Checks
        if: env.LAUNCH_STYLELINT == 'on'
        run: yarn stylelint

  typecheckApps:
    name: Type Check Apps for Preview
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      # Currently, tsc && reviewdog is will not display properly in conversation review.
      - name: Do Type Check
        if: env.LAUNCH_TYPECHECK == 'on'
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: apps
          level: warning
          fail_on_error: true
          filter_mode: nofilter
      # - name: Displayed Tsc Failure on Checks
      #   if: env.LAUNCH_TYPECHECK == 'on'
      #   run: |
      #     yarn tsc --noEmit

  typecheckClient:
    name: Type Check Client for Preview
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      # Currently, tsc && reviewdog is will not display properly in conversation review.
      - name: Do Type Check
        if: env.LAUNCH_TYPECHECK == 'on'
        uses: EPMatt/reviewdog-action-tsc@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: client
          level: warning
          fail_on_error: true
          filter_mode: nofilter
      # - name: Displayed Tsc Failure on Checks
      #   if: env.LAUNCH_TYPECHECK == 'on'
      #   run: |
      #     yarn tsc --noEmit

  jest:
    name: Jest
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Set Env
        run: |
          if ls apps/resource/tests/*.test.ts > /dev/null 2>&1 || ls apps/resource/tests/*.test.js > /dev/null 2>&1 || ls client/resource/tests/*.test.ts > /dev/null 2>&1 || ls client/resource/tests/*.test.js > /dev/null 2>&1
          then
              echo "FILE_EXISTS=on" >> $GITHUB_ENV
          else
              echo "FILE_EXISTS=off" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Do Jest
        if: env.LAUNCH_JEST == 'on' && env.FILE_EXISTS == 'on'
        run: yarn jest

  build:
    name: Build Test
    needs:
      - setup
      - cspell
      - eslint
      - stylelint
      - typecheckApps
      - typecheckClient
      - jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Execution Environment for Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Restore Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-v${{ env.NODE_VERSION }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Do Build Test
        if: env.LAUNCH_BUILD == 'on'
        run: yarn build
